version: "3"
services:
  pmetaload:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /my/videos/to/upload:/video
      - /my/torrent/incoming:/output
    environment:
      - ANNOUNCEURL=http://tracker.lan/1234
      #- BROWSEROOT=/video # only if you need another folder
      - TORRENTPATH=/output #if you dont want to copy, delete this line
      #- SELENIUMURL=http://MyCustomSeleniumBrowser:4444/wd/hub # only if you have selenium already running somewhere
  selenium:
    image: selenium/standalone-chrome:3.12.0-cobalt
    volumes:
      - /dev/shm:/dev/shm
